# Generated by Django 4.1.7 on 2023-02-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistika',
            old_name='umumiy_sana',
            new_name='umumiy_summa',
        ),
    ]
